# Generated by Django 4.2.30 on 2026-04-09 11:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import health_analytic_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=health_analytic_service.models.generate_api_key, max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable label for this key.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ssn_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255, unique=True)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('REGISTRATION', 'Registration'), ('TRIAGE', 'Triage'), ('BED_ASSIGNMENT', 'Bed Assignment'), ('TREATMENT', 'Treatment'), ('DISPOSITION', 'Disposition'), ('DEPARTURE', 'Departure')], max_length=30, null=True)),
                ('acuity_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('chief_complaint', models.CharField(blank=True, max_length=500, null=True)),
                ('disposition', models.CharField(blank=True, choices=[('DISCHARGED', 'Discharged'), ('ADMITTED', 'Admitted'), ('TRANSFERRED', 'Transferred'), ('LEFT_WITHOUT_TREATMENT', 'Left Without Treatment')], max_length=30, null=True)),
                ('diagnosis_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='health_analytic_service.patient')),
            ],
            options={
                'ordering': ['-timestamp', 'record_id'],
            },
        ),
    ]
