# Generated by Django 4.2.30 on 2026-04-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('health_analytic_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='analytics.visit'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['timestamp', 'facility'], name='ix_record_ts_facility'),
        ),
    ]
