# Generated by Django 4.2.30 on 2026-04-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_analytic_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_at', models.DateTimeField(blank=True, null=True)),
                ('triage_at', models.DateTimeField(blank=True, null=True)),
                ('bed_assignment_at', models.DateTimeField(blank=True, null=True)),
                ('treatment_at', models.DateTimeField(blank=True, null=True)),
                ('disposition_at', models.DateTimeField(blank=True, null=True)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete')], default='IN_PROGRESS', max_length=20)),
                ('is_registration_missing', models.BooleanField(default=False, help_text='True when no REGISTRATION event was found for this visit.')),
                ('is_departure_missing', models.BooleanField(default=False, help_text='True when no DEPARTURE event was found for this visit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='health_analytic_service.patient')),
            ],
            options={
                'ordering': ['-registration_at'],
                'indexes': [models.Index(fields=['status', 'is_registration_missing', 'is_departure_missing'], name='ix_visit_status_flags')],
            },
        ),
    ]
